### PR TITLE
fix bug in uprading clusternet-hub and clusternet-agent

### PR DESCRIPTION
**Pull request by willzgli**
Kubernetes doesn't allow RoleRef of ClusterRoleBinding(or RoleBinding) to be updated

Change name of clusterrolebinding, to keep uprading smoothly

### CODE REVIEW

**Comment by willzgli** [comment]
with old name, uprade will fail, the error as bellow
image

**Comment by dixudx** [comment]
@willzgli Shall we use `helm upgrade --force` to help reinstall those changed role/clusterrole bindings.

**Comment by dixudx** [comment]
helm/helm#6468 had a debate on this problem. That was an intentional design decision in Helm. Users need to either manually intervene or use the `--force` flag when they want to opt into destructive actions such as re-creating the object when they want to change an immutable field.

**Comment by willzgli** [comment]
> [helm/helm#6468](https://github.com/helm/helm/issues/6468) had a debate on this problem. That was an intentional design decision in Helm. Users need to either manually intervene or use the `--force` flag when they want to opt into destructive actions such as re-creating the object when they want to change an immutable field.

yes , --force is destructive.  We should provide a more secure and automatic uprading path for older clustenet version

**Pull request merged**
